name: Postman API Testing
on:
  push:
    branches: [ "main" ]
  pull_request:
      branches: [ "main" ]
  
jobs:
  Api-Testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        Nodev: [16,18]
    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v4 
      
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.Nodev}}
      
      - name: Install newman and report
        run: npm install -g newman 

      - name: Run Newman
        run: newman run postman_tests/Books.postman_collection.json -e postman_tests\test.postman_environment.json

